dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
- node
after_success:
- npm run coveralls
notifications:
  slack:
    secure: 3CIoX+F5cEadScG6tmUieXcEMG2VwUIM3rmvgT/5db0SoHBUsRa4PNrmdf9lcu06ohZI8nwq8mHXfYBS7enPzm9Gw5WdTC2L2DVbmXTbyv5cyWUReuHe1mrxTJeIgaUQfB0d4WTMo5UQL+gF1TUJe2rDtePXtcsRKKToWypSAZ3aPFvfeQwPd4O2JJJIr+ZCqbqNZ0ca6x13IPG+z8DWpEmZ1A7gnaK2s41r+4kN7XNpiSdRy6H3yEdLoh/kgsk5vQmUGEGEBVch4Z7f8zloskOpF3eMCip9+fFSU3mV6Vk09QiIp/3PBV5jvy8b5OHVx+dq679sAThGFYS/MpRBAjpBsw5cLmuBmk4fqUj+QQkolJZVnsM+iPHLzrd1oj+ePBDI4dp69t3kxPlu8cezORX9fl7m+AedmR8MV+yufk+8jd6xfySK+sNCKfLr/Iaw5OHnUZfuU+SvBZIRMdYBlMczzTotrg7avDUw4gJK1D6zOAGMmofba/8EqrjDSFLiKbvkQUfhkguusWED0hPAo/YGCXgMSSQZqI0YMTzz5M1oNJpC8klZTqU2f9ZRXODoGZnkAfr3z7sO5whaClIuzsi0Ya/TVYcWLtaUoT43PbddcAA5P8ysbiBfN2ajaYyyLWXsf4//ZMOWFfjcomCPEDlwxfVgABfSD06QU/NzoBU=
deploy:
  provider: npm
  email: ryanhelmoski@gmail.com
  skip_cleanup: true
  api_key:
    secure: "ZyQN1bAcX9dOOnYucNGqb+meTajIOHRn9vfIxKC6NRxIHlHn5NuzhONKWfVc3qT3nClSJ4hfSw4rQwPDcAxO9uTRYKjYaVyFlVbQ9L2F6Jks2cToQN26OumkZ/uAjq8hbomx83TXCeOBeecJv/+1u0KRiYORyhoR0d3WQPCUj/NOi4umnvqLNhagUas6h6LhLQGX2O3inlgSgApLgBh5M6KtYCmU2nOW96CgvO3xGbufbTuAHSK8u2XEZjD7vgcclnF+Op3P5+9RarZFO9luRSSopxcrrIiV1fconjD/Eg8DukWidHrKHZbxvID6nVT6Q1goCrmCh4w0MzkDgfad8rnkllA+H3JFAzxZhHBxj0mdv/zVq8DtFCCNaqbALXX6/NLPoMcdZAjXblMJpoNNiqR3E/7T+3EsL8JSS63ew/He6dACsrZQToXLUaTmLcnzePIbSBWs8pOmE143Z7/HJDr1T2g1Ovt9XejZ07vNToEQZOmfAc+X2FOmymLpUNRZORJtvBod8iZgK7o8Ja+msrayGZ9f2Ga8FxOx075hfBR6wC9UyUikTAUF5rcuWuqWYnAiN4arshJdxxsheyUjBnMrgn8tMaI131coEAxghqNH4pT31cJy6W8Ful9cN5cWRLfqUxm+25VZ2UYapGMQl8Fd9IOI+fOQsNbd7fHw4co="
  on:
    tags: true
    all_branches: true
    repo: helmoski/cycle-selection-driver
