dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
- node
after_success:
- npm run coveralls
notifications:
  slack:
    secure: 3CIoX+F5cEadScG6tmUieXcEMG2VwUIM3rmvgT/5db0SoHBUsRa4PNrmdf9lcu06ohZI8nwq8mHXfYBS7enPzm9Gw5WdTC2L2DVbmXTbyv5cyWUReuHe1mrxTJeIgaUQfB0d4WTMo5UQL+gF1TUJe2rDtePXtcsRKKToWypSAZ3aPFvfeQwPd4O2JJJIr+ZCqbqNZ0ca6x13IPG+z8DWpEmZ1A7gnaK2s41r+4kN7XNpiSdRy6H3yEdLoh/kgsk5vQmUGEGEBVch4Z7f8zloskOpF3eMCip9+fFSU3mV6Vk09QiIp/3PBV5jvy8b5OHVx+dq679sAThGFYS/MpRBAjpBsw5cLmuBmk4fqUj+QQkolJZVnsM+iPHLzrd1oj+ePBDI4dp69t3kxPlu8cezORX9fl7m+AedmR8MV+yufk+8jd6xfySK+sNCKfLr/Iaw5OHnUZfuU+SvBZIRMdYBlMczzTotrg7avDUw4gJK1D6zOAGMmofba/8EqrjDSFLiKbvkQUfhkguusWED0hPAo/YGCXgMSSQZqI0YMTzz5M1oNJpC8klZTqU2f9ZRXODoGZnkAfr3z7sO5whaClIuzsi0Ya/TVYcWLtaUoT43PbddcAA5P8ysbiBfN2ajaYyyLWXsf4//ZMOWFfjcomCPEDlwxfVgABfSD06QU/NzoBU=
deploy:
  provider: npm
  email: ryanhelmoski@gmail.com
  skip_cleanup: true
  api_key:
    secure: UPtp1JrpQrjTwB1FKE8eEv51tq7CVhPaKemCkRiWQDdaURzGUR6Mk6DBFtfR8JibxrQ8olgZ/PdoiyWytqgCCuACjKqiGWXIkUmBgTOl09ezdxDbZizESD34uMrazrrMwJymGzkSJKfotIdSR+UzQxIjv2WM/yqO9LSzzGvufv2aQxd+IsEVwX4AQijISfc50rGzNOdX+PmhN5O7CWEfWkDJLMLw7IXwF7EniAmX8lKLTeWWF2jYPRPjKx0JgM+ch/YcS6uB6tP/pV0jz9L3TzaPV7t/IVfock7YbQFYsxM2Sj7lNhlfC7Wnjs3gFPxRbBnZI2ki+u11vx31Ou2d/jC7mrbC0ASGfVvnJ9VBnONmp0ySV6Q6uXUEhO5DtITMhAMirIKbhLx+S+0IHlakCKelohseC+BgfcnCGy2Tt1ThZXV3igcB8yGITKIjriZLaBirNBuoml4+2MGeu2RgcObwz+KIBCb8z0rNZUzclDveYhqKvEjHIG9xxBkoGJVLhPAJ+Mt+APf2tCmEjJLMvsNOcQkUXgMO1v8A8YQRuUpuLpH4tcHdgMOJYN0bU8fFNSbMa3oufatnAUmEthWlP9wtXFkL3iOgdpi5LoDbAmg3K/3Hp2Ry55w1GDmcm5/ZWGOVSxWQF02h8D+ejyFOni3pmlQ5gUpBJ7hPhc9JySo=
  on:
    tags: true
    all_branches: true
    repo: helmoski/cycle-selection-driver
